### ISSUE TITLE
Not an issue; How to run this

### ISSUE THREAD

**Issue by Gomesz785** [hekinami/sazparser#2]
like how to get this to work?

**Comment by hekinami** [comment]
This is simply a python 3 script which parses the specified saz file by unziping it and extract information from the files in directory structure.

This simple script extract saz  information from the structure described in https://web.archive.org/web/20180730023102/http://fiddler.wikidot.com:80/saz-files and calculate some based on the information.  Not all information are extrated in this script, but you can use it as a clue to write your own.

**Comment by Gomesz785** [comment]
Can you elaborate more on instructions for a windows computor? I have python 3 and VScode.

**Comment by hekinami** [comment]
I updated the readme file a little and you could follow it to check how it work. 


I am a linux user and have no windows environment on hand, but I think the steps should be exactly the same. If you are not familar with how to prepare python and pip then you should go to python.org to  get instructions about how to install them into windows.


I am sorry that this script is not a perfect tool that could be used out-of-box, it's a script that show the main idea for how to extract information from saz files, so you  need write your own (specifiying the fields you need) for your work, basing on this example.

**Comment by hekinami** [comment]
I think the questions mentioned have been answered, so close.

**Comment by Gomesz785** [comment]
> I think the questions mentioned have been answered, so close.

Sorry I was away at iFixit. Yes close.
